name: Check pgq LOC

on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  count-loc:
    runs-on: ubuntu-latest
    steps:
      - name: Install cloc
        run: sudo apt-get update && sudo apt-get install -y cloc

      - name: Clone Latest Tag
        run: |
          git clone https://github.com/MikuX-Dev/pgq folder

      - name: LOC for Entire Repo
        run: |
          cd folder
          echo "=== LOC: Entire Repository ==="
          cloc . --exclude-dir=.git,tmp,log --not-match-f='.*\.spec\.js'

   #   - name: Find and Count LOC for Each Top-Level Directory
    #    run: |
     #     cd forgejo
     #     echo "=== LOC: By Top-Level Folder ==="
      #    for dir in */ ; do
     #       # skip if not a directory or hidden git folder
     #       if [ -d "$dir" ] && [ "$dir" != ".git/" ]; then
    #          echo "--- $dir ---"
     #         cloc "$dir" --exclude-dir=.git,tmp,log --not-match-f='.*\.spec\.js'
     #       fi
     #     done
